### PR TITLE
Generate random numbers for each radiation call

### PR DESCRIPTION
**Pull request by SallyDa**
When using RRTMG with McICA, generate random numbers (determining which wavelengths see cloud and which do not) each time the radiation is called and heating rates are calculated. This means that for a state that does not change, calling the radiation multiple times gives different fluxes and heating rates each time, as different wavelengths are subject to different conditions (cloud or no cloud). Averaging over multiple calls is a better approximation of the true atmosphere, where all wavelengths see some cloud.

Sorry I didn't put much thought into this when first including the option of using mcica!

### CODE REVIEW

**Comment by JoyMonteiro** [comment]
Sorry for the huge delay, but this looks good to me too!

**Comment by SallyDa** [comment]
That's fine and thanks a lot!

Unfortunately we're not sure it's working for the shortwave. Here is some code that illustrates the issue.

```radlw = climt.RRTMGLongwave(mcica=True, cloud_optical_properties='direct_input')
radsw = climt.RRTMGShortwave(mcica=True, cloud_optical_properties='direct_input')
state = climt.get_default_state([radlw, radsw])
# put a cloud somewhere
state['shortwave_optical_thickness_due_to_cloud'] += 1
state['longwave_optical_thickness_due_to_cloud'] += 1
state['cloud_area_fraction_in_atmospheric_layer'][15:18] = 0.4
# calculate fluxes and heating rates twice
lw_tendency1 = radlw(state)[1]['air_temperature_tendency_from_longwave']
lw_tendency2 = radlw(state)[1]['air_temperature_tendency_from_longwave']
sw_tendency1 = radsw(state)[1]['air_temperature_tendency_from_shortwave']
sw_tendency2 = radsw(state)[1]['air_temperature_tendency_from_shortwave']
# if the wavelengths are allocated randomly to see or not see cloud, I would expect 
# the tendencies to change every time 
np.allclose(lw_tendency1, lw_tendency2)  # gives False, as expected
np.allclose(sw_tendency1, sw_tendency2)  # gives True
```

So far, I haven't been able to spot an obvious mistake... It would be great if you could find time to have another look through (if not that's also okay, but I thought you should be aware of this anyway). It is also possible that the issue is inside RRTMG itself, or perhaps it should actually be like that, but that seems unlikely to me.

**Comment by JoyMonteiro** [comment]
Hmm OK. I will give myself a week to look at this. If I don't find the time, I will keep the PR with master open until we are able to decide one way or the other. Sorry again for the delays at my end, is a very busy time right now.

**Comment by SallyDa** [comment]
That's absolutely fine! Lukas and I are the ones who want to use it, not you, so I really appreciate you taking some time to look at it :)

**Pull request merged**
