### PR TITLE
Merge McICA fix

### PR DESCRIPTION
**Pull request by JoyMonteiro**
changes the random number for each call so that a distribution of heating rates
can be generated every time RRTMG is called.

### CODE REVIEW

**Comment by JoyMonteiro** [comment]
@SallyDa @lkluft sorry about the huge delay in getting back. I expect this will be the case until end of August.

In any case, I went through the code and have a few comments.

* The code mentions that it is desirable for successive seeds to be separated by at least number of g-points.
* The code also mentions that the permute seed for LW and SW should be separated by a similar amount.

Therefore, I suggest adding in some logic to separate permute seeds by at least that amount.
maybe something like
```
self._permute_seed = self._old_permute_seed + (rand_int + 1)*num_reduced_g_intervals
```

I also found the issue with the SW not changing its output with this new code.
Turns out that the order of the arguments in the python wrapper is incorrect.
In 
https://github.com/CliMT/climt/blob/ddc6530a754d6778634b65ce3b93c9fabdf1f799/climt/_components/rrtmg/sw/component.py#L518-L519

random_number_generator should be the last argument according to the cython wrapper.
This change should fix the issue you are facing.

Finally, could you also create a dictionary for the argument for the random number generator in the python components? It has been put down as a TODO.

**Comment by SallyDa** [comment]
@JoyMonteiro, thank you so much for going through this! Sorry for my mistake with the argument order, I thought I had checked that a few times already, so thanks a lot for finding it. I'll work on the changes and get back to you soon.

**Comment by lkluft** [comment]
Thank you very much for your feedback and for finding the issue with the SW, @JoyMonteiro!

I thought about the requirements for the permute seed and came up with the following solution:
```python
step = num_reduced_g_intervals
self._permute_seed = (self._old_permute_seed + np.random.randint(step, 500 - step)) % 500
```

It preserves the mean and standard deviation, stays within the limits, and ensures a minimum distance of within consecutive seeds.

Current distribution
rand_old

New distribution
rand_new

**Comment by SallyDa** [comment]
Nice, thanks @lkluft . I've changed the dictionary already, so if you get the branch `random` from my fork you can add just add the changes to the `permute_seed`, update the cached output for the tests and make a pr?

**Comment by SallyDa** [comment]
By the way, there is no particular reason why I specified that the random number should be less than 500, but I just thought that it shouldn't be arbitrarily large.

**Pull request merged**
